let  
Source = Table.FromColumns({Lines.FromBinary(Web.Contents("http://www.nemweb.com.au/REPORTS/CURRENT/",[RelativePath = "Dispatch_SCADA/" ]), null, null, 65001)}),
    #"Removed Top Rows" = Table.Skip(Source,2),
    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Top Rows", {{"Column1", Splitter.SplitTextByDelimiter("HREF", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Column1"),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column1", type text}}),
    #"Removed Top Rows1" = Table.Skip(#"Changed Type",3),
    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Removed Top Rows1", "Text Between Delimiters", each Text.BetweenDelimiters([Column1], "/", ">", 3, 0), type text),
    #"Filtered Rows2" = Table.SelectRows(#"Inserted Text Between Delimiters", each ([Text Between Delimiters] <> "DUPLICATE/")),
    #"'Filtered Rows'" = Table.SelectColumns(#"Filtered Rows2",{"Text Between Delimiters"}),
  #"Sorted rows" = Table.Sort(#"'Filtered Rows'", {{"Text Between Delimiters", Order.Descending}}),
  buffer = Table.Buffer(#"Sorted rows" ),
  #"Kept top rows" = Table.FirstN(buffer, 10),
    #"Renamed Columns" = Table.RenameColumns(#"Kept top rows",{{"Text Between Delimiters", "Children.Text"}}),
  #"Removed other columns 1" = Table.SelectColumns(#"Renamed Columns", {"Children.Text"}),
    #"Added Custom" = Table.AddColumn(#"Removed other columns 1", "ZIP", each Web.Contents("http://www.nemweb.com.au/REPORTS/CURRENT/", [RelativePath = "Dispatch_SCADA/" & [Children.Text]])),
    #"Invoked Custom Function" = Table.AddColumn(#"Added Custom", "ZipContents", each UnzipContents([ZIP])),
#"Expanded ZipContents" = Table.ExpandTableColumn(#"Invoked Custom Function", "ZipContents", {"FileName", "Content"}, {"ZipContents.FileName", "ZipContents.Content"}),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Expanded ZipContents", each [Attributes]?[Hidden]? <> true),
    #"Added Custom1" = Table.AddColumn(#"Filtered Hidden Files1", "Custom", each Csv.Document([ZipContents.Content],[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom1",{"Children.Text", "Custom"}),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Other Columns1", "Custom", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20"}),
    #"Removed Top Rows2" = Table.Skip(#"Expanded Custom",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows2", [PromoteAllScalars=true]),
    #"Renamed Columns2" = Table.RenameColumns(#"Promoted Headers",{{Table.ColumnNames(#"Promoted Headers"){0}, "file"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns2",{"file", "SETTLEMENTDATE", "DUID", "SCADAVALUE"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns", each ([SETTLEMENTDATE] <> "PUBLIC" and [SETTLEMENTDATE] <> "SETTLEMENTDATE")),
    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows1",{{"SETTLEMENTDATE", type datetime}, {"SCADAVALUE", type number}, {"DUID", type text}})
in
    #"Changed Type1"
